# docker-compose.yml
version: "4"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
      - /home/ec2-user/s3-solaradoutput/Fenice/:/home/Fenice/
      - /home/ec2-user/s3-solaradoutput/csv/clients/:/home/csv/


  postgres:
    image: postgres:15
    volumes:
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      - ./tmp/db:/var/lib/postgresql@15/data:rw
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db