# docker-compose.yml
version: "4"
services:
  app:
    restart: on-failure
    build: .
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "80:3000"
    command: npm run dev
    volumes:
      - /home/ec2-user/efs-solarad-output/csv/clients:/home/Forecast/
      - /home/ec2-user/efs-solarad-output/Fenice/:/home/Fenice/