version: "4"
services:
  app:
    restart: on-failure
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "80:3000"
    command: npm run dev
    volumes:
      - .:/app/
      - /app/node_modules
      - /home/ubuntu/efs_solaradoutput/csv/clients:/home/Forecast/
      - /home/ubuntu/efs_solaradoutput/Fenice/:/home/Fenice/
      - /home/ubuntu/efs_solaradoutput/csv/clients/:/home/csv/

  postgres:
    image: postgres:15
    volumes:
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      - ./tmp/db:/var/lib/postgresql/data:rw  # Corrected this line
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db

volumes:
  pgdata:
